project:
  type: website

website:
  title: "ISSS608-G1"
  navbar:
    left:
      - text: "Proposal"
        menu: 
        - text: "Project Proposal"
          href: "proposal/proposal.html"
        
      - text: "Prototype"
        menu: 
        - text:'Data Preperation'
          href:"prototype/data_preperation/data_preperation.html"
        - text: "EDA"
          href: "prototype/EDA/eda.html"
        - text: "Clustering"
          href: "prototype/modeling/clustering.html"
      
      - text: "Project"
        menu: 
        - text: "website"
          href: "project/website.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

